name: pylint check

on:
  push:
    branches: [ develop, v2.0 ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  pylint:
    name: pylint check
    runs-on: 'ubuntu-24.04'
    steps:
    - name: checkout software
      uses: actions/checkout@v2
      with:
        path: software
    - name: 'refresh install'
      run: |
        sudo apt-get update --fix-missing
    - name: 'install python3 pylint'
      run: |
        sudo apt-get install --fix-broken --ignore-missing pylint
    - name: 'show pylint directories'
      run: |
        find . -type d
        pylint --version
    - name: 'make lint (pylint static source code checking)'
      id: check
      run: |
        make lint -C software PYLINT=pylint PYLINT_OPTIONS=--disable=unknown-option-value
    